name: Sync Leetcode

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Code from LeetCode
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          verbose: true

      - name: Auto-Categorize into README Topics Table
        uses: kamyu104/leetcode-badge@v2.2.0
        with:
          github-token: ${{ github.token }}
          user-name: 'siddharthshukla17' # Your LeetCode username
