name: Sync Leetcode

on:
  push:
    branches:
      - main     # Triggers the dashboard generation on every push to main
      - master   # Triggers if your main branch is named master
  workflow_dispatch: # Keeps the manual button just in case

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Code from LeetCode
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          verbose: true

      - name: Auto-Generate Topic Table README
        uses: dennisvash/leetcode-action@v1.2
        with:
          github-token: ${{ github.token }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          filter-duplicate-solutions: true
          update-readme: true
