name: Sync Leetcode

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync Code from LeetCode
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          verbose: true

      - name: Update Repository Index
        uses: gautamkrishnar/todo-to-issue-action@v2024.11.1
        continue-on-error: true # Ensures this step never crashes your script

      - name: Auto-Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update leetcode solutions table [skip ci]"
